### ISSUE TITLE
Unreachable executed on wasm

### ISSUE THREAD

**Issue by noomly** [ryanisaacg/quicksilver#443]
When I run the game I am developing I get lots of "unreachable executed" errors and the game is frozen on the first frame. Here is the complete error message on chromium:

```
rustydowndown.js:474 Uncaught RuntimeError: unreachable
    at std::panicking::rust_panic_with_hook::hf1dedd3caf5a4d24 (wasm-function[874]:132)
    at std::panicking::continue_panic_fmt::hb0f54927fec60fb9 (wasm-function[873]:122)
    at rust_begin_unwind (wasm-function[872]:3)
    at core::panicking::panic_fmt::hca5dc4e8b320bc56 (wasm-function[1003]:70)
    at core::result::unwrap_failed::h696cc54e8257d001 (wasm-function[215]:137)
    at _$LT$stdweb..webcore..newtype..Newtype$LT$$LP$stdweb..webcore..serialization..FunctionTag$C$$u20$$LP$A12$C$$RP$$RP$$C$$u20$stdweb..webcore..mutfn..Mut$LT$F$GT$$GT$$u20$as$u20$stdweb..webcore..serialization..FuncallAdapter$LT$F$GT$$GT$::funcall_adapter::h5572578ab9cf6d43 (wasm-function[143]:1684)
    at Object.Module.STDWEB_PRIVATE.dyncall (http://localhost:8000/rustydowndown.js:474:40)
    at HTMLCanvasElement.output (http://localhost:8000/rustydowndown.js:174:39)
```

I am under the impression that it has something to do with events, as the error gets printed again when I move the mouse over the canvas, or when I press keys, etc. Unfortunately, other than that, I have no idea about what's happening here since the console error are not giving a lot of informations.

As I don't know what exactly is causing the problem, I can't produce a simple code that reproduce the error. However the code of the game is accessible here: https://gitlab.com/noom/rustydowndown . So, to reproduce the error, just clone it and run `cargo web start` then go to http://localhost:8000 .

- Environment: Archlinux, Firefox 65.0, Chromium 71.0.3578.98
- Rust compiler version: stable 1.31.1
- Quicksilver version: 0.3.4

**Comment by noomly** [comment]
I just figured out the problem...

I was printing the FPS in the console with `println!("FPS: {}", window.current_fps());` in my update function, which caused the crash for some reasons.

I don't remember seeing this documented anywhere? If It is not, maybe it should?
