### ISSUE TITLE
Unable to load font as an asset

### ISSUE THREAD

**Issue by khanage** [ryanisaacg/quicksilver#485]
I've just started dabbling with `quicksilver` and I'm trying to render some text to the screen. The [example for loading fonts and rendering them](https://docs.rs/quicksilver/0.3.11/quicksilver/tutorials/_07_font/index.html) hardcodes the text during the `new` implementation.

I'm trying to dynamically render text, but if I pass the font inside an asset I get the following error:

```
→ cargo run
   Compiling quicksilverdemon v0.1.0 (/Users/khan/dev/quicksilverdemon)
    Finished dev [unoptimized + debuginfo] target(s) in 2.82s
     Running `target/debug/quicksilverdemon`
thread 'main' panicked at 'Unhandled error: IOError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', /Users/khan/.cargo/registry/src/github.com-1ecc6299db9ec823/quicksilver-0.3.11/src/lifecycle/state.rs:44:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:336
   7: quicksilver::lifecycle::state::State::handle_error
             at /Users/khan/dev/quicksilverdemon/<::std::macros::panic macros>:8
   8: quicksilver::lifecycle::run::run_with
             at /Users/khan/.cargo/registry/src/github.com-1ecc6299db9ec823/quicksilver-0.3.11/src/lifecycle/run.rs:53
   9: quicksilver::lifecycle::run::run
             at /Users/khan/.cargo/registry/src/github.com-1ecc6299db9ec823/quicksilver-0.3.11/src/lifecycle/run.rs:40
  10: quicksilverdemon::main
             at src/main.rs:36
  11: std::rt::lang_start::{{closure}}
             at /rustc/8aaae4294b16b8070a52b858364f440873bfc95c/src/libstd/rt.rs:64
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  13: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:85
  14: std::panicking::update_count_then_panic
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  15: std::rt::lang_start
             at /rustc/8aaae4294b16b8070a52b858364f440873bfc95c/src/libstd/rt.rs:64
  16: quicksilverdemon::main
```

**To Reproduce**

I've created a repo [to reproduce the issue](https://github.com/khanage/quicksilver-font-load/blob/master/Cargo.lock)

Just a `cargo run` will compile and dump out straight away.

**Environment and versions:**

I'm on macOS mojave, with quicksilver 0.3.11, and the following `rustc -Vv`:
 ```
rustc 1.36.0-nightly (8aaae4294 2019-04-19)
binary: rustc
commit-hash: 8aaae4294b16b8070a52b858364f440873bfc95c
commit-date: 2019-04-19
host: x86_64-apple-darwin
release: 1.36.0-nightly
LLVM version: 8.0
```

**Comment by ryanisaacg** [comment]
Looks like the issue is that you have 'font.tff' instead of 'font.ttf.' The error message should definitely include what file it failed to load, though; I'll work on adding that.
