### ISSUE TITLE
Unable to find file?

### ISSUE THREAD

**Issue by nico-abram** [ryanisaacg/quicksilver#511]
I have a file `e.gba` inside `project/static/`. 
I get the following error:
```

thread 'main' panicked at 'aasd: IOError(Os { code: 2, kind: NotFound, message: "El sistema no puede encontrar el archivo especificado." })', src\libcore\result.rs:999:5
stack backtrace:
   0: std::sys_common::backtrace::_print
             at /rustc/088b987307b91612ab164026e1dcdd0129fdb62b\/src\libstd\sys_common\backtrace.rs:47
   1: std::panicking::default_hook::{{closure}}
             at /rustc/088b987307b91612ab164026e1dcdd0129fdb62b\/src\libstd\panicking.rs:200
   2: std::panicking::default_hook
             at /rustc/088b987307b91612ab164026e1dcdd0129fdb62b\/src\libstd\panicking.rs:216
   3: std::panicking::rust_panic_with_hook
             at /rustc/088b987307b91612ab164026e1dcdd0129fdb62b\/src\libstd\panicking.rs:477
   4: std::panicking::continue_panic_fmt
             at /rustc/088b987307b91612ab164026e1dcdd0129fdb62b\/src\libstd\panicking.rs:384
   5: std::panicking::rust_begin_panic
             at /rustc/088b987307b91612ab164026e1dcdd0129fdb62b\/src\libstd\panicking.rs:311
   6: core::panicking::panic_fmt
             at /rustc/088b987307b91612ab164026e1dcdd0129fdb62b\/src\libcore\panicking.rs:85
   7: core::result::unwrap_failed<quicksilver::error::QuicksilverError>
             at /rustc/088b987307b91612ab164026e1dcdd0129fdb62b\src\libcore\macros.rs:18
   8: core::result::Result<(), quicksilver::error::QuicksilverError>::expect<(),quicksilver::error::QuicksilverError>
             at /rustc/088b987307b91612ab164026e1dcdd0129fdb62b\src\libcore\result.rs:827
   9: rusty_boy_advance_quicksilver::main
             at .\src\main.rs:37
  10: std::rt::lang_start::{{closure}}<core::result::Result<(), alloc::boxed::Box<Error>>>
             at /rustc/088b987307b91612ab164026e1dcdd0129fdb62b\src\libstd\rt.rs:64
  11: std::panicking::try::do_call<closure,i32>
             at /rustc/088b987307b91612ab164026e1dcdd0129fdb62b\/src\libstd\panicking.rs:296
  12: panic_unwind::__rust_maybe_catch_panic
             at /rustc/088b987307b91612ab164026e1dcdd0129fdb62b\/src\libpanic_unwind\lib.rs:82
  13: std::rt::lang_start_internal
             at /rustc/088b987307b91612ab164026e1dcdd0129fdb62b\/src\libstd\rt.rs:48
  14: std::rt::lang_start<core::result::Result<(), alloc::boxed::Box<Error>>>
             at /rustc/088b987307b91612ab164026e1dcdd0129fdb62b\src\libstd\rt.rs:64
  15: main
  16: __scrt_common_main_seh
             at d:\agent\_work\2\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  17: BaseThreadInitThunk
  18: RtlUserThreadStart
error: process didn't exit successfully
```
When trying to run
```rs
  let mut r = Asset::new(quicksilver::load_file("e.gba"));
  r.execute(|rom_file| {
    do_useful_stuff(rom_file);
    Ok(())
  })?;
```
I expected this to work since the docs state `All Quicksilver file loading-APIs will expect paths that originate in the static folder,`. Looking at what load_file does, it ends up being this for non wasm:
```

#[cfg(not(target_arch="wasm32"))]
fn load(path: impl AsRef<Path>) -> Result<Vec<u8>> {
    let mut data = Vec::new();
    File::open(path)?.read_to_end(&mut data)?;
    Ok(data)
}
```
Shouldn't that be using /static? Using a full path in the call to load_file like "C:\\......\\test-quicksilver\\static\\e.gba" seems to make it work (But it obviously won't work i the brower). Is there some other file loading api I should be using?

**Comment by ryanisaacg** [comment]
Hi, without seeing more of your project structure I'm not what the issue you're facing is.

On desktop, Quicksilver changes directory into 'static/' so all paths can be considered relative to 'static/'.

**Comment by nico-abram** [comment]
I'm using a workspace with a library crate and a number of binary crates that use it, one of which is quicksilvr. Could that be related?

**Comment by ryanisaacg** [comment]
That's probably related, can you print the [current directory](https://doc.rust-lang.org/std/env/fn.current_dir.html) and see if it matches the directory where 'static' is?

Also, is there a message printed to stdout / stderr about Quicksilver not finding static?

**Comment by nico-abram** [comment]
There is no error about it (If i delete the folder, there is).

**Comment by ryanisaacg** [comment]
If this issue persists with the new file loading API, please let me know and re-open.
