### ISSUE TITLE
Can't install for the first time

### ISSUE THREAD

**Issue by painttist** [ryanisaacg/quicksilver#524]
Hi I was installing quicksilver for the first time on macOS, was following the instructions on README, created a new rust project via `cargo new`, added dependency `quicksilver = "*"
` in `Cargo.toml` and then replaced the `src/main.rs` file with the sample code, and then `cargo run`

And the process failed, showing me the following:
```
| => cargo run
   Compiling semver-parser v0.7.0
   Compiling libc v0.2.60
   Compiling memchr v2.2.1
   Compiling proc-macro2 v0.4.30
...(Other Compiling)
   Compiling coreaudio-sys v0.2.2
   Compiling lyon v0.13.5
   Compiling winit v0.19.2
error: failed to run custom build command for `coreaudio-sys v0.2.2`

Caused by:
  process didn't exit successfully: `/Users/(username)/Desktop/Mystuff/All Projects/2019/test/test1/target/debug/build/coreaudio-sys-5915fc4271c5c2cc/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-lib=framework=AudioUnit
cargo:rustc-link-lib=framework=CoreAudio

--- stderr
/usr/local/include/Block.h:16:3: error: Never include this file directly. Use <lzma.h> instead.
/usr/local/include/Block.h:93:2: error: unknown type name 'lzma_check'
/usr/local/include/Block.h:148:2: error: unknown type name 'lzma_vli'
/usr/local/include/Block.h:172:2: error: unknown type name 'lzma_vli'
/usr/local/include/Block.h:200:2: error: unknown type name 'lzma_filter'
/usr/local/include/Block.h:217:20: error: use of undeclared identifier 'LZMA_CHECK_SIZE_MAX'
/usr/local/include/Block.h:231:2: error: unknown type name 'lzma_vli'
/usr/local/include/Block.h:232:2: error: unknown type name 'lzma_vli'
/usr/local/include/Block.h:233:2: error: unknown type name 'lzma_vli'
/usr/local/include/Block.h:234:2: error: unknown type name 'lzma_vli'
/usr/local/include/Block.h:235:2: error: unknown type name 'lzma_vli'
/usr/local/include/Block.h:236:2: error: unknown type name 'lzma_vli'
/usr/local/include/Block.h:237:2: error: unknown type name 'lzma_reserved_enum'
/usr/local/include/Block.h:238:2: error: unknown type name 'lzma_reserved_enum'
/usr/local/include/Block.h:239:2: error: unknown type name 'lzma_reserved_enum'
/usr/local/include/Block.h:240:2: error: unknown type name 'lzma_reserved_enum'
/usr/local/include/Block.h:261:2: error: unknown type name 'lzma_bool'
/usr/local/include/Block.h:263:2: error: unknown type name 'lzma_bool'
/usr/local/include/Block.h:264:2: error: unknown type name 'lzma_bool'
fatal error: too many errors emitted, stopping now [-ferror-limit=]
/usr/local/include/Block.h:16:3: error: Never include this file directly. Use <lzma.h> instead., err: true
/usr/local/include/Block.h:93:2: error: unknown type name 'lzma_check', err: true
/usr/local/include/Block.h:148:2: error: unknown type name 'lzma_vli', err: true
/usr/local/include/Block.h:172:2: error: unknown type name 'lzma_vli', err: true
/usr/local/include/Block.h:200:2: error: unknown type name 'lzma_filter', err: true
/usr/local/include/Block.h:217:20: error: use of undeclared identifier 'LZMA_CHECK_SIZE_MAX', err: true
/usr/local/include/Block.h:231:2: error: unknown type name 'lzma_vli', err: true
/usr/local/include/Block.h:232:2: error: unknown type name 'lzma_vli', err: true
/usr/local/include/Block.h:233:2: error: unknown type name 'lzma_vli', err: true
/usr/local/include/Block.h:234:2: error: unknown type name 'lzma_vli', err: true
/usr/local/include/Block.h:235:2: error: unknown type name 'lzma_vli', err: true
/usr/local/include/Block.h:236:2: error: unknown type name 'lzma_vli', err: true
/usr/local/include/Block.h:237:2: error: unknown type name 'lzma_reserved_enum', err: true
/usr/local/include/Block.h:238:2: error: unknown type name 'lzma_reserved_enum', err: true
/usr/local/include/Block.h:239:2: error: unknown type name 'lzma_reserved_enum', err: true
/usr/local/include/Block.h:240:2: error: unknown type name 'lzma_reserved_enum', err: true
/usr/local/include/Block.h:261:2: error: unknown type name 'lzma_bool', err: true
/usr/local/include/Block.h:263:2: error: unknown type name 'lzma_bool', err: true
/usr/local/include/Block.h:264:2: error: unknown type name 'lzma_bool', err: true
fatal error: too many errors emitted, stopping now [-ferror-limit=], err: true
thread 'main' panicked at 'unable to generate bindings: ()', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

Backtrace:
```
| => RUST_BACKTRACE=1 cargo run
   Compiling ncollide2d v0.19.2
   Compiling serde_json v1.0.40
   Compiling coreaudio-sys v0.2.2
   Compiling glutin v0.21.0
error: failed to run custom build command for `coreaudio-sys v0.2.2`

Caused by:
  process didn't exit successfully: `/Users/(username)/Desktop/Mystuff/All Projects/2019/test/test1/target/debug/build/coreaudio-sys-5915fc4271c5c2cc/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-lib=framework=AudioUnit
cargo:rustc-link-lib=framework=CoreAudio

--- stderr
/usr/local/include/Block.h:16:3: error: Never include this file directly. Use <lzma.h> instead.
/usr/local/include/Block.h:93:2: error: unknown type name 'lzma_check'
/usr/local/include/Block.h:148:2: error: unknown type name 'lzma_vli'
/usr/local/include/Block.h:172:2: error: unknown type name 'lzma_vli'
/usr/local/include/Block.h:200:2: error: unknown type name 'lzma_filter'
/usr/local/include/Block.h:217:20: error: use of undeclared identifier 'LZMA_CHECK_SIZE_MAX'
/usr/local/include/Block.h:231:2: error: unknown type name 'lzma_vli'
/usr/local/include/Block.h:232:2: error: unknown type name 'lzma_vli'
/usr/local/include/Block.h:233:2: error: unknown type name 'lzma_vli'
/usr/local/include/Block.h:234:2: error: unknown type name 'lzma_vli'
/usr/local/include/Block.h:235:2: error: unknown type name 'lzma_vli'
/usr/local/include/Block.h:236:2: error: unknown type name 'lzma_vli'
/usr/local/include/Block.h:237:2: error: unknown type name 'lzma_reserved_enum'
/usr/local/include/Block.h:238:2: error: unknown type name 'lzma_reserved_enum'
/usr/local/include/Block.h:239:2: error: unknown type name 'lzma_reserved_enum'
/usr/local/include/Block.h:240:2: error: unknown type name 'lzma_reserved_enum'
/usr/local/include/Block.h:261:2: error: unknown type name 'lzma_bool'
/usr/local/include/Block.h:263:2: error: unknown type name 'lzma_bool'
/usr/local/include/Block.h:264:2: error: unknown type name 'lzma_bool'
fatal error: too many errors emitted, stopping now [-ferror-limit=]
/usr/local/include/Block.h:16:3: error: Never include this file directly. Use <lzma.h> instead., err: true
/usr/local/include/Block.h:93:2: error: unknown type name 'lzma_check', err: true
/usr/local/include/Block.h:148:2: error: unknown type name 'lzma_vli', err: true
/usr/local/include/Block.h:172:2: error: unknown type name 'lzma_vli', err: true
/usr/local/include/Block.h:200:2: error: unknown type name 'lzma_filter', err: true
/usr/local/include/Block.h:217:20: error: use of undeclared identifier 'LZMA_CHECK_SIZE_MAX', err: true
/usr/local/include/Block.h:231:2: error: unknown type name 'lzma_vli', err: true
/usr/local/include/Block.h:232:2: error: unknown type name 'lzma_vli', err: true
/usr/local/include/Block.h:233:2: error: unknown type name 'lzma_vli', err: true
/usr/local/include/Block.h:234:2: error: unknown type name 'lzma_vli', err: true
/usr/local/include/Block.h:235:2: error: unknown type name 'lzma_vli', err: true
/usr/local/include/Block.h:236:2: error: unknown type name 'lzma_vli', err: true
/usr/local/include/Block.h:237:2: error: unknown type name 'lzma_reserved_enum', err: true
/usr/local/include/Block.h:238:2: error: unknown type name 'lzma_reserved_enum', err: true
/usr/local/include/Block.h:239:2: error: unknown type name 'lzma_reserved_enum', err: true
/usr/local/include/Block.h:240:2: error: unknown type name 'lzma_reserved_enum', err: true
/usr/local/include/Block.h:261:2: error: unknown type name 'lzma_bool', err: true
/usr/local/include/Block.h:263:2: error: unknown type name 'lzma_bool', err: true
/usr/local/include/Block.h:264:2: error: unknown type name 'lzma_bool', err: true
fatal error: too many errors emitted, stopping now [-ferror-limit=], err: true
thread 'main' panicked at 'unable to generate bindings: ()', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:308
   7: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/macros.rs:18
   9: core::result::Result<T,E>::expect
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/result.rs:827
  10: build_script_build::build
             at ./build.rs:139
  11: build_script_build::main
             at ./build.rs:155
  12: std::rt::lang_start::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  13: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  14: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:85
  15: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  16: std::rt::lang_start
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  17: build_script_build::main

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Environment and versions:**
- Environment: macOS Mojave
- Rust compiler version: stable 1.36.0
- Quicksilver verison: 0.3.18

Please help! Thank!

**Comment by ryanisaacg** [comment]
That's very odd! I mostly develop Quicksilver on macOS Mojave, and have had no problems. It's possible that installing [Xcode](https://developer.apple.com/xcode/) will do the trick by providing some platform developer library, can you try that and let me know if it helps?

**Comment by painttist** [comment]
I have Xcode version 10.3 (10G8) installed already. Following your instruction, I updated it, and also made a quick audio test app but sadly the sample code build still doesn't run, printing out the same error.

**Comment by ryanisaacg** [comment]
I think this is outside the bounds of what I can help with; can you try reporting the issue to the [coreaudio-sys](https://github.com/RustAudio/coreaudio-sys) project directly to see if they can help?

**Comment by painttist** [comment]
I see, thanks!
